# coding: utf-8

"""
    Lexico Service

    API for managing words in the lexico service

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class WordUpdate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, word=None, audio=None, synonyms=None):
        """
        WordUpdate - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'word': 'str',
            'audio': 'str',
            'synonyms': 'list[str]'
        }

        self.attribute_map = {
            'word': 'word',
            'audio': 'audio',
            'synonyms': 'synonyms'
        }

        self._word = word
        self._audio = audio
        self._synonyms = synonyms

    @property
    def word(self):
        """
        Gets the word of this WordUpdate.
        Updated name of the word

        :return: The word of this WordUpdate.
        :rtype: str
        """
        return self._word

    @word.setter
    def word(self, word):
        """
        Sets the word of this WordUpdate.
        Updated name of the word

        :param word: The word of this WordUpdate.
        :type: str
        """

        self._word = word

    @property
    def audio(self):
        """
        Gets the audio of this WordUpdate.
        Updated URL to the audio pronunciation of the word

        :return: The audio of this WordUpdate.
        :rtype: str
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """
        Sets the audio of this WordUpdate.
        Updated URL to the audio pronunciation of the word

        :param audio: The audio of this WordUpdate.
        :type: str
        """

        self._audio = audio

    @property
    def synonyms(self):
        """
        Gets the synonyms of this WordUpdate.
        Updated list of synonyms

        :return: The synonyms of this WordUpdate.
        :rtype: list[str]
        """
        return self._synonyms

    @synonyms.setter
    def synonyms(self, synonyms):
        """
        Sets the synonyms of this WordUpdate.
        Updated list of synonyms

        :param synonyms: The synonyms of this WordUpdate.
        :type: list[str]
        """

        self._synonyms = synonyms

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
